---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pretendapp
  namespace: identity-demo
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  backend:
    serviceName: pretendapp
    servicePort: 80
