---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pretendapp
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
  - http:
      paths:
      - path: /
        pathtype: Prefix
        backend:
          serviceName: pretendapp
          servicePort: 80

